@startuml
abstract class BaseAction {
    + {abstract} GetActionName() : string
    + {abstract} TakeAction(gridPosition:GridPosition, onActionComplete:Action) : void
    + <<virtual>> IsValidActionGridPosition(gridPosition:GridPosition) : bool
    + {abstract} GetValidActionGridPositionList() : List<GridPosition>
    + <<virtual>> GetActionPointCost() : int
}
MonoBehaviour <|-- BaseAction
@enduml
