@startuml
class MoveAction {
    + <<override>> TakeAction(gridPosition:GridPosition, onActionComplete:Action) : void
    + <<override>> GetValidActionGridPositionList() : List<GridPosition>
    + <<override>> GetActionName() : string
}
BaseAction <|-- MoveAction
@enduml
